---
title: "Project 3"
author: "Mark Gonsalves"
date: "10/16/2020"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(RMySQL)
library(DBI)
```

## Project 3



## Steps
1) We first pulled the data from Kaggle.com and moved the 2 DB's to our github account.
2) Then we imported the files into MySQL.  
3) From MySQL, we will now pull the data into R.
4) After the data connection was made with MySQL and R, we have then created 2 new dataframes: "db1" and "db2".
5) 


```{r}
JobSkills <- DBI::dbConnect(RMySQL::MySQL(), dbname = "DataScience", user="root", port=3306, host='localhost', password="1dodger1")

dbListTables(JobSkills)
glimpse(JobSkills)

class(dbGetQuery(JobSkills,"SHOW TABLES"))
dbGetQuery(JobSkills, "SHOW TABLES")
dbGetQuery(JobSkills, "EXPLAIN ds_general_skills_revised")
dbGetQuery(JobSkills, "EXPLAIN indeed_job_dataset")

db1 <-dbGetQuery(JobSkills, "SELECT * FROM ds_general_skills_revised")
db2 <-dbGetQuery(JobSkills, "SELECT * FROM indeed_job_dataset")

head(db1,15)
head(db2,15)
```
```{r}

```

