

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(RMySQL)
library(tidyverse)
library(magrittr)
library(reshape2)
library(knitr)
```

```{r mysql setup}
db <- dbConnect(MySQL(), user='root', password=.rs.askForPassword("Enter password:"), 
                dbname='project_3', host='localhost')

summary(db)

#lists the tables in the database
dbListTables(db)

#assigning variables to each table
indeed <- dbReadTable(db, "indeed")
general_skills <- na.omit(dbReadTable(db, "general_skills"))
```

### Frequency of Skills
```{r}
indeed_skills <- indeed$Skill %>% 
  str_remove_all("\\[|\\]|\\'") %>%
  str_trim() %>%
  str_split(",") %>%
  unlist() %>%
  str_trim() %>%
  table() %>%
  as.data.frame() %>%
  set_colnames(c("skill", "frequency")) %>%
  arrange(desc(frequency)) %>%
  mutate(proportion = frequency / sum(frequency))

#graph of top 15 skills overall
indeed_skills %>%
  slice(1:15) %>%
ggplot(., aes(x = reorder(skill, frequency), y = frequency)) +
  geom_bar(stat = "identity") +
  coord_flip() +
  ggtitle("Top 15 Skills overall") +
  xlab("skill")

```

### SKills vs Job Type
```{r, warnings = FALSE}
#subsetting data
job_vs_skill <- indeed %>% 
  select(Job_Type, Skill) 

#cleaning skills column
job_vs_skill$Skill <- job_vs_skill$Skill %>%
  str_remove_all("\\[|\\]|\\'") %>%
  str_trim() %>%
  str_split(",") 

#cleaning job type columns
job_vs_skill$Job_Type <- job_vs_skill$Job_Type %>%
  str_replace_all("_", " ")

#unnesting   
job_vs_skill <- job_vs_skill %>% unnest(Skill) 

#removing white space
job_vs_skill$Skill <- trimws(job_vs_skill$Skill, which = c("both"))

#finding frequencies and proportions
job_vs_skill <- job_vs_skill %>%
  group_by(Job_Type, Skill) %>%
  summarise(freq = n()) %>%
  mutate(proportion = freq/ sum(freq),
         label = round(proportion * 100, 2))

#top 10 skills by job type redo
job_vs_skill %>%
  group_by(Skill) %>%
  mutate(overall = sum(freq)) %>%
  arrange(desc(overall)) %>%
  ungroup() %>%
  slice(1:45) %>%
ggplot(., aes(x = reorder(Skill, overall), y = freq, fill = Job_Type)) +
  geom_bar(stat = "identity", position = "dodge") +
  coord_flip() +
  theme(axis.text.x = element_blank(), axis.ticks = element_blank()) +
  xlab("skill") +
  ggtitle("Distribution of Skills by Job Type")

#top 10 skills by job type
job_vs_skill2 <- job_vs_skill %>%
  group_by(Job_Type) %>%
  top_n(10, proportion) %>%
  ungroup() %>%
  arrange(Job_Type, desc(proportion))

#graph of the top 10 skills by job type
ggplot(job_vs_skill2) + 
  geom_bar(aes(x = Skill, y = proportion, fill = Job_Type), stat = "identity", 
           position = position_fill(reverse = TRUE)) +
  coord_flip() +
  ggtitle("Distribution of Skills by Job Type")

#3 different graphs of top 10 skills by job type
ggplot(job_vs_skill2) + 
  geom_bar(aes(x = reorder(Skill, proportion), y = proportion, fill = Job_Type), stat = "identity") +
  coord_flip() +
  facet_wrap(~Job_Type, scales = "free") +
  ggtitle("Distribution of Skills by Job Type") +
  geom_text(aes(x = reorder(Skill, proportion), y = proportion, label = label, group = Job_Type),
            position = position_stack(vjust = .5, reverse = TRUE), size = 3) +
  theme(axis.text.x = element_blank(), axis.ticks = element_blank(), legend.position = "none")

#Data Scientist top 15 jobs
job_vs_skill %>%
  filter(Job_Type == "data scientist") %>%
  top_n(15, freq) %>%
  arrange(desc(freq))%>%
  select(-label) %>%
  kable()
```

```{r}
#subsetting data
ds_industry <- indeed %>% 
  select(Job_Type, Skill, Company_Industry) 

#cleaning skills column
ds_industry$Skill <- ds_industry$Skill %>%
  str_remove_all("\\[|\\]|\\'") %>%
  str_trim() %>%
  str_split(",") 

#unnesting   
ds_industry <- ds_industry %>% unnest(Skill) 

#removing white space
ds_industry$Skill <- trimws(ds_industry$Skill, which = c("both"))

#cleaning job type columns
ds_industry$Job_Type <- ds_industry$Job_Type %>%
  str_replace_all("_", " ") 

#finding frequencies and proportions
ds_industry <- ds_industry %>%
  filter(Job_Type == "data scientist") %>%
  group_by(Company_Industry, Skill) %>%
  summarise(freq = n()) %>%
  mutate(proportion = freq/ sum(freq),
         label = round(proportion * 100, 2))

#top 10 skills by company industry
ds_industry <- ds_industry %>%
  filter(Company_Industry %in% c("Consulting and Business Services", "Internet and Software",
                               "Banks and Financial Services", "Health Care", "Insurance")) %>%
  group_by(Company_Industry) %>%
  top_n(7, proportion) %>%
  ungroup() %>%
  arrange(Company_Industry, desc(proportion))

ggplot(ds_industry) + 
  geom_bar(aes(x = reorder(Skill, proportion), y = proportion, fill = Company_Industry), stat = "identity") +
  coord_flip() +
  facet_wrap(~Company_Industry, scales = "free", ncol = 2) +
  ggtitle("Distribution of Skills by Job Type") +
  geom_text(aes(x = reorder(Skill, proportion), y = proportion, label = label, group = Company_Industry),
            position = position_stack(vjust = .5, reverse = TRUE), size = 3) +
  theme(axis.text.x = element_blank(), axis.ticks = element_blank(), legend.position = "none") +
  ylab("") +
  xlab("Skill")
```

### General Skills
```{r}

```

